In [2]:
import pandas as pd
df = pd.DataFrame([[90, 60, 104, 95], [1, 1, 1], [2, 0, 2000], [2, 1, 10]], columns=list('ABC'))

In [5]:
import numpy as np

In [12]:
obs = np.array([[90, 60, 104, 95], [30, 50, 51, 20], [30, 40, 45, 35]])

In [23]:
obs2 = np.array([[90, 45, 181, 9], [30, 15, 61, 3], [30, 15, 59, 3]])
obs3 = np.array([[90, 45, 181, 90], [30, 15, 61, 3]]) #, [30, 15, 59, 3]
print(obs2)
print(obs3)

[[ 90  45 181   9]
 [ 30  15  61   3]
 [ 30  15  59   3]]
[[ 90  45 181  90]
 [ 30  15  61   3]]


In [33]:
from scipy.stats import chi2_contingency
chi2_contingency(obs3[:,0:2])


(0.0, 1.0, 1, array([[90., 45.],
        [30., 15.]]))

In [32]:
obs3[:,0:2]

array([[90, 45],
       [30, 15]])